VERSION = 0.5.93~UNRELEASED

DESTDIR =
LIBDIR := $(DESTDIR)/$(shell ocamlc -where)
BINDIR  = $(DESTDIR)/usr/bin
CLIBDIR = $(DESTDIR)/usr/lib
CINCDIR = $(DESTDIR)/usr/include
PCDIR   = $(DESTDIR)/usr/lib/pkgconfig
