VERSION = 0.5.94

export DESTDIR =
export OCAMLLIBDIR := $(DESTDIR)/$(shell ocamlc -where)
export BINDIR  = $(DESTDIR)/usr/bin
export LIBDIR = $(DESTDIR)/usr/lib
export INCDIR = $(DESTDIR)/usr/include
export PCDIR   = $(LIBDIR)/pkgconfig
