VERSION = 0.5.98

export DESTDIR = /tmp/cudf

# all the following variables will be prepended by $(DESTDIR) upon install

export OCAMLLIBDIR := $(shell ocamlc -where)
export BINDIR  = /usr/bin
export LIBDIR = /usr/lib
export INCDIR = /usr/include
export PCDIR   = $(LIBDIR)/pkgconfig
